"""Receipt reading and signature verification against the Go golden log.

testdata/receipts_golden.jsonl is generated by the Go proxy
(go test ./internal/store/ -run TestGoldenLog -update); these tests pin
the cross-language contract from the consuming side.
"""

import json
from contextlib import closing
from pathlib import Path
from typing import Any

import pytest
from envelopes import (
    GOLDEN,
    GOLDEN_KEYS,
    OTHER_KEYS,
    bodies,
    edit_body,
    edit_payload,
    golden_lines,
    signed_chain,
    write_log,
)

from vouch_verifier.index import build_index, facts_for
from vouch_verifier.receipts import ReceiptError, load_log


def test_load_golden_log_with_signatures() -> None:
    receipts = load_log(GOLDEN, GOLDEN_KEYS)
    assert [r.receipt_id for r in receipts] == ["golden-0", "golden-1", "golden-2"]

    r0 = receipts[0]
    assert r0.keyid == "ed25519:8bdc9a88e7cf36a6"
    assert r0.tool_name == "get_indicators"
    assert r0.session_id == "s-golden"
    assert r0.args_canonical == '{"symbol":"NVDA","timeframe":"1d"}'
    assert r0.data_asof == "2026-07-24T20:00:00Z"
    assert [f.metric for f in r0.facts] == ["rsi_14", "close_price"]
    assert r0.facts[0].value == 62.3
    assert r0.facts[1].unit == "USD"

    # Receipt without schema coverage: no facts, no data_asof, unicode intact.
    r2 = receipts[2]
    assert r2.facts == ()
    assert r2.data_asof is None
    assert "英伟达" in r2.result_canonical


def test_wrong_key_rejected() -> None:
    with pytest.raises(ReceiptError, match="no valid signature from a trusted key"):
        load_log(GOLDEN, OTHER_KEYS)


def test_tampered_value_rejected(tmp_path: Path) -> None:
    lines = golden_lines()
    # The deadly class: nudge a receipted value, leave everything else.
    tampered = edit_payload(lines[0], lambda body: body.replace("62.3", "68.1"))
    bad = write_log(tmp_path / "receipts.jsonl", [tampered, *lines[1:]])
    with pytest.raises(ReceiptError, match="line 1: no valid signature"):
        load_log(bad, GOLDEN_KEYS)


def test_editing_the_last_receipt_passes_structure_but_not_signatures(tmp_path: Path) -> None:
    # The chain catches an edit to any entry something later links to.
    # The last entry has no successor, so only its signature protects it.
    lines = golden_lines()
    tampered = edit_body(lines[2], lambda b: b.update(tool_name="get_other_tool"))
    bad = write_log(tmp_path / "receipts.jsonl", [lines[0], lines[1], tampered])
    assert load_log(bad)[-1].tool_name == "get_other_tool"
    with pytest.raises(ReceiptError, match="line 3: no valid signature"):
        load_log(bad, GOLDEN_KEYS)


def test_editing_an_earlier_receipt_breaks_the_chain_without_keys(tmp_path: Path) -> None:
    lines = golden_lines()
    tampered = edit_body(lines[0], lambda b: b.update(tool_name="get_other_tool"))
    bad = write_log(tmp_path / "receipts.jsonl", [tampered, *lines[1:]])
    with pytest.raises(ReceiptError, match="line 2: chain broken: prev_digest"):
        load_log(bad)


def test_duplicate_session_turn_rejected(tmp_path: Path) -> None:
    # A trusted key holder can build a valid chain with a replayed
    # (session_id, turn_index); the chain does not stop that, this does.
    (kind, body), _ = bodies(golden_lines()[:2])
    first = json.loads(body)
    log = signed_chain([(kind, first), (kind, {**first, "receipt_id": "golden-replayed"})])
    bad = write_log(tmp_path / "receipts.jsonl", log)
    with pytest.raises(ReceiptError, match="duplicate \\(session_id=s-golden, turn_index=0\\)"):
        load_log(bad)


def test_digest_mismatch_rejected(tmp_path: Path) -> None:
    tampered = edit_body(golden_lines()[0], lambda b: b.update(result_digest="sha256:" + "0" * 64))
    bad = write_log(tmp_path / "receipts.jsonl", [tampered])
    with pytest.raises(ReceiptError, match="digest"):
        load_log(bad)


def test_index_lookup() -> None:
    receipts = load_log(GOLDEN, GOLDEN_KEYS)
    with closing(build_index(receipts)) as conn:
        hits = facts_for(conn, "NVDA", "rsi_14", "1d")
        assert len(hits) == 1
        receipt_id, fact = hits[0]
        assert receipt_id == "golden-0"
        assert fact.value == 62.3
        assert fact.tol_class == "indicator"

        # Timeframe None matches any timeframe.
        assert len(facts_for(conn, "AMD", "last_price")) == 1
        assert facts_for(conn, "TSLA", "rsi_14") == []


def test_golden_receipts_bind_the_response() -> None:
    # Issue #20: the Go proxy records the whole result the agent saw.
    receipts = load_log(GOLDEN, GOLDEN_KEYS)
    for r in receipts:
        assert r.payload_source == "structuredContent"
        assert r.response_canonical is not None and r.response_digest is not None
        assert r.result_canonical in r.response_canonical


def test_tampered_response_is_rejected_without_a_key(tmp_path: Path) -> None:
    def edit(body: dict[str, Any]) -> None:
        body["response_canonical"]["content"][0]["text"] = "NVDA RSI is 12.0"

    bad = write_log(tmp_path / "receipts.jsonl", [edit_body(golden_lines()[0], edit)])
    with pytest.raises(ReceiptError, match="response_digest"):
        load_log(bad)
