"""Receipt reading and signature verification against the Go golden log.

testdata/receipts_golden.jsonl is generated by the Go proxy
(go test ./internal/store/ -run TestGoldenLog -update); these tests pin
the cross-language contract from the consuming side.
"""

import json
from pathlib import Path

import pytest

from vouch_verifier.index import build_index, facts_for
from vouch_verifier.receipts import ReceiptError, load_log, verify_receipt

GOLDEN = Path(__file__).parent.parent.parent / "testdata" / "receipts_golden.jsonl"
KEY = b"vouch-golden-key"


def test_load_golden_log_with_signatures():
    receipts = load_log(GOLDEN, key=KEY)
    assert [r.receipt_id for r in receipts] == ["golden-0", "golden-1", "golden-2"]

    r0 = receipts[0]
    assert r0.tool_name == "get_indicators"
    assert r0.session_id == "s-golden"
    assert r0.args_canonical == '{"symbol":"NVDA","timeframe":"1d"}'
    assert r0.data_asof == "2026-07-24T20:00:00Z"
    assert [f.metric for f in r0.facts] == ["rsi_14", "close_price"]
    assert r0.facts[0].value == 62.3
    assert r0.facts[1].unit == "USD"

    # Receipt without schema coverage: no facts, no data_asof, unicode intact.
    r2 = receipts[2]
    assert r2.facts == ()
    assert r2.data_asof is None
    assert "英伟达" in r2.result_canonical


def test_wrong_key_rejected():
    with pytest.raises(ReceiptError, match="signature"):
        load_log(GOLDEN, key=b"wrong-key")


def test_tampered_value_rejected(tmp_path):
    lines = GOLDEN.read_text().splitlines()
    # The deadly class: nudge a receipted value, leave everything else.
    tampered = lines[0].replace("62.3", "68.1")
    assert tampered != lines[0]
    bad = tmp_path / "receipts.jsonl"
    bad.write_text("\n".join([tampered] + lines[1:]) + "\n")
    with pytest.raises(ReceiptError):
        load_log(bad, key=KEY)


def test_tampered_receipt_fails_verify_not_load(tmp_path):
    # Tampering that keeps digest/result consistent still breaks the HMAC.
    line = json.loads(GOLDEN.read_text().splitlines()[1])
    line["tool_name"] = "get_totally_different_tool"
    bad = tmp_path / "receipts.jsonl"
    bad.write_text(json.dumps(line) + "\n")
    receipts = load_log(bad)  # structural load without key succeeds
    assert not verify_receipt(receipts[0], KEY)


def test_duplicate_session_turn_rejected(tmp_path):
    lines = GOLDEN.read_text().splitlines()
    bad = tmp_path / "receipts.jsonl"
    bad.write_text(lines[0] + "\n" + lines[0] + "\n")
    with pytest.raises(ReceiptError, match="duplicate"):
        load_log(bad)


def test_digest_mismatch_rejected(tmp_path):
    line = json.loads(GOLDEN.read_text().splitlines()[0])
    line["result_digest"] = "sha256:" + "0" * 64
    bad = tmp_path / "receipts.jsonl"
    bad.write_text(json.dumps(line) + "\n")
    with pytest.raises(ReceiptError, match="digest"):
        load_log(bad)


def test_index_lookup():
    receipts = load_log(GOLDEN, key=KEY)
    conn = build_index(receipts)

    hits = facts_for(conn, "NVDA", "rsi_14", "1d")
    assert len(hits) == 1
    receipt_id, fact = hits[0]
    assert receipt_id == "golden-0"
    assert fact.value == 62.3
    assert fact.tol_class == "indicator"

    # Timeframe None matches any timeframe.
    assert len(facts_for(conn, "AMD", "last_price")) == 1
    assert facts_for(conn, "TSLA", "rsi_14") == []
